'use strict';

// Renders each .vil source in src/ into a stacked ASCII-art visual keymap,
// one Markdown file per source, written into layouts/.
//
// Physical column order is read straight from the array itself (see
// scripts/lib/vil-json.js and the -1 sentinel for "no physical key here"),
// not inferred from any design doc. Per half, the array's column index runs
// from that half's outer edge to the center gap (confirmed against
// dist/default.vil), so the left half prints in array order and the right
// half prints reversed — that puts both halves' outer edges at the far left
// and right of the page, with the center gap in the middle. Rows are
// printed straight, without the keyboard's physical column stagger.

const fs = require('fs');
const path = require('path');
const vil = require('./lib/vil-json');
const { label } = require('./lib/keycode-labels');

const SRC_DIR = path.join(__dirname, '..', 'src');
const OUT_DIR = path.join(__dirname, '..', 'layouts');

const CELL_WIDTH = 6;
const HALF_GAP = '   │   ';

function cell(code) {
  const text = label(code);
  const padding = Math.max(0, CELL_WIDTH - text.length);
  const left = Math.floor(padding / 2);
  const right = padding - left;
  return `[${' '.repeat(left)}${text}${' '.repeat(right)}]`;
}

function renderRow(leftRow, rightRow) {
  const left = leftRow.filter(c => c !== -1).map(cell).join(' ');
  const right = [...rightRow]
    .reverse()
    .filter(c => c !== -1)
    .map(cell)
    .join(' ');
  return `${left}${HALF_GAP}${right}`;
}

function renderLayer(layer) {
  const [l1, l2, l3, lThumb, r1, r2, r3, rThumb] = layer;
  return [renderRow(l1, r1), renderRow(l2, r2), renderRow(l3, r3), '', renderRow(lThumb, rThumb)].join('\n');
}

fs.mkdirSync(OUT_DIR, { recursive: true });

const files = fs.readdirSync(SRC_DIR).filter(f => f.endsWith('.vil'));
if (files.length === 0) {
  console.error(`No .vil files found in ${SRC_DIR}`);
  process.exit(1);
}

for (const file of files) {
  const srcPath = path.join(SRC_DIR, file);
  const obj = vil.parse(fs.readFileSync(srcPath, 'utf8'));
  const base = path.basename(file, '.vil');

  const sections = obj.layout.map((layer, i) => `## Layer ${i}\n\n\`\`\`\n${renderLayer(layer)}\n\`\`\``);

  const md =
    [
      `# ${base}.vil — Visual Layout`,
      `Auto-generated by \`scripts/render-layouts.js\` from \`src/${file}\`. Do not edit by hand — re-run the script instead.`,
      ...sections,
    ].join('\n\n') + '\n';

  const outPath = path.join(OUT_DIR, `${base}.md`);
  fs.writeFileSync(outPath, md);
  console.log(`rendered ${path.relative(process.cwd(), outPath)}`);
}
